### PR TITLE
Added minor changes to JwtProvider

### PR DESCRIPTION
**Pull request by victoradepoju**

### CODE REVIEW

**Comment by victoradepoju** [comment]
I casted the auth.getPrincipal() to a User object before getting the email. This ensures the proper email field from the User model is added to the jwt claim. The previous method is returning the string representation of the User object, not the actual email address.

**Comment by NaveenChandraAdhikari** [comment]
Using auth.getName() instead of directly accessing a user object (like theUser user = (User)auth.getPrincipal()) can be more flexible, as it works regardless of the exact type of Authentication implementation that code is using ..right??

**Comment by NaveenChandraAdhikari** [comment]
ACTUALLY TO FETCH THE EMAIL I HAVE CHANGED THE FIELD savedUser.getEmail IN AUTHCONTROLLER.java. its working fine 

    authentication = new UsernamePasswordAuthenticationToken(savedUser.getEmail(), savedUser.getPassword());

**Comment by NaveenChandraAdhikari** [comment]
Can you fix the issue related to firstName showing  null

**Comment by victoradepoju** [comment]
> Using auth.getName() instead of directly accessing a user object (like theUser user = (User)auth.getPrincipal()) can be more flexible, as it works regardless of the exact type of Authentication implementation that code is using ..right??

No. You're trying to get the authenticated user stored in the security context. Spring sees it as an object but an authenticated user can ONLY be a User instance, so there is no need for any flexibility since it can and should only be a user object if authenticated correctly. So casting to User is necessary. Also without casting, you can't get a string value. You only get a reference object like you were getting before: e.g User@234rtf7

**Comment by victoradepoju** [comment]
> ACTUALLY TO FETCH THE EMAIL I HAVE CHANGED THE FIELD savedUser.getEmail IN AUTHCONTROLLER.java. its working fine
> 
> ```
> authentication = new UsernamePasswordAuthenticationToken(savedUser.getEmail(), savedUser.getPassword());
> ```

This was the way you fixed it before?

**Comment by victoradepoju** [comment]
> Can you fix the issue related to firstName showing null

If you merge this pull request, the issue of firstName showing null should also be fixed together.

**Comment by NaveenChandraAdhikari** [comment]
> > ACTUALLY TO FETCH THE EMAIL I HAVE CHANGED THE FIELD savedUser.getEmail IN AUTHCONTROLLER.java. its working fine
> > ```
> > authentication = new UsernamePasswordAuthenticationToken(savedUser.getEmail(), savedUser.getPassword());
> > ```
> 
> This was the way you fixed it before?

yeah it is showing the email

**Comment by NaveenChandraAdhikari** [comment]
> > Using auth.getName() instead of directly accessing a user object (like theUser user = (User)auth.getPrincipal()) can be more flexible, as it works regardless of the exact type of Authentication implementation that code is using ..right??
> 
> No. You're trying to get the authenticated user stored in the security context. Spring sees it as an object but an authenticated user can ONLY be a User instance, so there is no need for any flexibility since it can and should only be a user object if authenticated correctly. So casting to User is necessary. Also without casting, you can't get a string value. You only get a reference object like you were getting before: e.g User@234rtf7

actually i am generating the token using the email, auth.getName() is sufficient and appropriate RIGHT??

**Comment by NaveenChandraAdhikari** [comment]
@victoradepoju, I fixed the FIRSTNAME issue. It was a typo error in my Postman API body. Thanks for the assist. I will reach out for your advice again.

**Comment by victoradepoju** [comment]
> @victoradepoju, I fixed the FIRSTNAME issue. It was a typo error in my Postman API body. Thanks for the assist. I will reach out for your advice again.

Ok that's good to hear. I'd create some issues that I feel should be addressed generally when I'm less busy. Quite occupied for now, but should be very soon.

**Comment by NaveenChandraAdhikari** [comment]
All done with the issues🙂👍

**Pull request closed without merging**
